# Application Name
spring.application.name=ShopEase

# Application Port
server.port=8087

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/shopease_db?createDatabaseIfNotExist=true
spring.datasource.username=Deepansh
spring.datasource.password=Deepansh@18
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mail Configuration (Example settings, user needs to fill)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=deepanshshakya669@gmail.com
spring.mail.password=frhkdutxutmzajit
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Razorpay Configuration
razorpay.key.id=rzp_test_Rh6bb3NRMiHTtB
razorpay.key.secret=2ClF8EQwoDRJbLhlGwP3eLVf

# Application Settings
logging.level.org.hibernate.SQL=DEBUG
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Disable Thymeleaf cache for development
spring.thymeleaf.cache=false
